# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclidean_dense <- function(query, target) {
    .Call('_scPlotSimplex_euclidean_dense', PACKAGE = 'scPlotSimplex', query, target)
}

euclidean_sparse <- function(query, target) {
    .Call('_scPlotSimplex_euclidean_sparse', PACKAGE = 'scPlotSimplex', query, target)
}

euclideanColNorms <- function(x) {
    .Call('_scPlotSimplex_euclideanColNorms', PACKAGE = 'scPlotSimplex', x)
}

cosine_dense <- function(query, target) {
    .Call('_scPlotSimplex_cosine_dense', PACKAGE = 'scPlotSimplex', query, target)
}

cosine_sparse <- function(query, target) {
    .Call('_scPlotSimplex_cosine_sparse', PACKAGE = 'scPlotSimplex', query, target)
}

